# Generated by Django 6.0.4 on 2026-06-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'permissions': [('can_manage_blog', 'Может управлять блогом (создавать, редактировать, удалять)')], 'verbose_name': 'блоговая запись', 'verbose_name_plural': 'блоговые записи'},
        ),
    ]
