# Generated by Django 6.0.4 on 2026-06-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_product_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_unpublish_product', 'Может отменять публикацию продукта')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
